---
- name: Update ubuntu package cache
  apt: update_cache=true
- name: Upgrade existing packages
  apt: upgrade=full state=latest
- name: Install common packages
  apt: name={{ item }} state=latest
  with_items:
    - wget
    - curl
    - build-essential
    - git
    - unzip
    - openssh-server
    - openssh-blacklist
    - openssh-blacklist-extra
    - openssl
    - unattended-upgrades
    - sockstat
    - htop
- name: Configure periodic security updates
  copy: src={{ item.src }} dest={{ item.dest }} backup=true
  with_items:
    - { src: 'files/10periodic', dest: '/etc/apt/apt.conf.d/10periodic' }
    - { src: 'files/50unattended-upgrades', dest: '/etc/apt/apt.conf.d/50unattended-upgrades' }  

